// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuscuAPI.Infrastructure.Data;

#nullable disable

namespace MuscuAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MuscuAPI.Domain.Entities.DifficulteExercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Niveau");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("DifficultesExercices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pour les personnes qui commencent la musculation",
                            IsActive = true,
                            Niveau = 1,
                            Nom = "Débutant"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nécessite quelques mois de pratique",
                            IsActive = true,
                            Niveau = 2,
                            Nom = "Intermédiaire"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pour les pratiquants expérimentés",
                            IsActive = true,
                            Niveau = 3,
                            Nom = "Avancé"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mouvements complexes nécessitant une excellente maîtrise",
                            IsActive = true,
                            Niveau = 4,
                            Nom = "Expert"
                        });
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conseils")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DifficulteId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MuscleId")
                        .HasColumnType("int");

                    b.Property<int>("MusclePrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TypeEquipementId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DifficulteId");

                    b.HasIndex("MuscleId");

                    b.HasIndex("MusclePrincipalId");

                    b.HasIndex("Nom");

                    b.HasIndex("TypeEquipementId");

                    b.ToTable("Exercices", (string)null);
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.ExerciceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId", "Ordre");

                    b.ToTable("ExercicesImages", (string)null);
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.ExerciceMuscleSecondaire", b =>
                {
                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdreImportance")
                        .HasColumnType("int");

                    b.HasKey("ExerciceId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("ExercicesMusclesSecondaires", (string)null);
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.GroupeMusculaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("GroupesMusculaires", (string)null);
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fonction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupeMusculaireId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomLatin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupeMusculaireId");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Muscles", (string)null);
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.TypeEquipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.HasIndex("Ordre");

                    b.ToTable("TypesEquipements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exercices au poids du corps",
                            IsActive = true,
                            Nom = "Aucun équipement",
                            Ordre = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Poids libres modulables",
                            IsActive = true,
                            Nom = "Haltères",
                            Ordre = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Barre olympique ou EZ",
                            IsActive = true,
                            Nom = "Barre",
                            Ordre = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Machines guidées",
                            IsActive = true,
                            Nom = "Machine",
                            Ordre = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Câbles et poulies",
                            IsActive = true,
                            Nom = "Poulie",
                            Ordre = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bandes de résistance",
                            IsActive = true,
                            Nom = "Élastique/Bande",
                            Ordre = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Poids avec poignée",
                            IsActive = true,
                            Nom = "Kettlebell",
                            Ordre = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pour tractions et suspensions",
                            IsActive = true,
                            Nom = "Barre de traction",
                            Ordre = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Banc de musculation",
                            IsActive = true,
                            Nom = "Banc",
                            Ordre = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ballon de gym",
                            IsActive = true,
                            Nom = "Swiss Ball",
                            Ordre = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sangles de suspension",
                            IsActive = true,
                            Nom = "TRX",
                            Ordre = 11
                        });
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.Exercice", b =>
                {
                    b.HasOne("MuscuAPI.Domain.Entities.DifficulteExercice", "Difficulte")
                        .WithMany("Exercices")
                        .HasForeignKey("DifficulteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuscuAPI.Domain.Entities.Muscle", null)
                        .WithMany("ExercicesPrincipal")
                        .HasForeignKey("MuscleId");

                    b.HasOne("MuscuAPI.Domain.Entities.Muscle", "MusclePrincipal")
                        .WithMany()
                        .HasForeignKey("MusclePrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuscuAPI.Domain.Entities.TypeEquipement", "TypeEquipement")
                        .WithMany("Exercices")
                        .HasForeignKey("TypeEquipementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Difficulte");

                    b.Navigation("MusclePrincipal");

                    b.Navigation("TypeEquipement");
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.ExerciceImage", b =>
                {
                    b.HasOne("MuscuAPI.Domain.Entities.Exercice", "Exercice")
                        .WithMany("Images")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.ExerciceMuscleSecondaire", b =>
                {
                    b.HasOne("MuscuAPI.Domain.Entities.Exercice", "Exercice")
                        .WithMany("MusclesSecondaires")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuscuAPI.Domain.Entities.Muscle", "Muscle")
                        .WithMany("ExercicesSecondaire")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.Muscle", b =>
                {
                    b.HasOne("MuscuAPI.Domain.Entities.GroupeMusculaire", "GroupeMusculaire")
                        .WithMany("Muscles")
                        .HasForeignKey("GroupeMusculaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupeMusculaire");
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.DifficulteExercice", b =>
                {
                    b.Navigation("Exercices");
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.Exercice", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("MusclesSecondaires");
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.GroupeMusculaire", b =>
                {
                    b.Navigation("Muscles");
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.Muscle", b =>
                {
                    b.Navigation("ExercicesPrincipal");

                    b.Navigation("ExercicesSecondaire");
                });

            modelBuilder.Entity("MuscuAPI.Domain.Entities.TypeEquipement", b =>
                {
                    b.Navigation("Exercices");
                });
#pragma warning restore 612, 618
        }
    }
}
